# Generated by Django 6.0.1 on 2026-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('experience', models.IntegerField()),
                ('current_house_yrs', models.IntegerField()),
                ('cur_job_years', models.IntegerField()),
                ('marital_status', models.CharField(choices=[('married', 'Married'), ('single', 'Single')], max_length=10)),
                ('house_ownership', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('none', 'No House')], max_length=10)),
                ('car_ownership', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('region', models.CharField(choices=[('north_india', 'North'), ('south_india', 'South'), ('west_india', 'West'), ('east_india', 'East'), ('central_india', 'Central'), ('north_east_india', 'Northeast')], max_length=20)),
                ('job_category', models.CharField(choices=[('Engineering', 'Engineering'), ('Technology & IT', 'Technology & IT'), ("'IT, Data & Analytics'", 'IT, Data & Analytics'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Creative, Design & Media', 'Creative, Design & Media'), ('Law, Government & Public Service', 'Law, Government & Public Service'), ('Business, Finance & Administration', 'Business, Finance & Administration'), ('Aviation, Defense & Security', 'Aviation, Defense & Security'), ('Education, Research & Documentation', 'Education, Research & Documentation'), ('Hospitality & Services', 'Hospitality & Services')], max_length=50)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('risk_flag', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
