# Generated by Django 6.0.1 on 2026-02-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0002_analystnote_loanapplication_delete_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='house_ownership',
            field=models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('norent_noown', 'No House No Rent')], max_length=15),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='region',
            field=models.CharField(choices=[('North India', 'North'), ('South India', 'South'), ('West India', 'West'), ('East India', 'East'), ('Central India', 'Central'), ('North-East India', 'Northeast')], max_length=20),
        ),
    ]
