# Generated by Django 6.0.1 on 2026-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0004_analystprofile_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
