# Generated by Django 6.0.1 on 2026-05-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0005_loanapplication_loan_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ai_prediction',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
