# Generated by Django 6.0.1 on 2026-05-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0006_remove_loanapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystnote',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
