# Generated by Django 6.0.1 on 2026-06-19 12:58

import loan_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='age',
            field=models.IntegerField(validators=[loan_manager.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='cur_job_years',
            field=models.IntegerField(validators=[loan_manager.models.validate_job_years]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='current_house_yrs',
            field=models.IntegerField(validators=[loan_manager.models.validate_house_years]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='experience',
            field=models.IntegerField(validators=[loan_manager.models.validate_experience]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income',
            field=models.FloatField(validators=[loan_manager.models.validate_income]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='job_category',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Technology & IT', 'Technology & IT'), ('IT, Data & Analytics', 'IT, Data & Analytics'), ('Healthcare & Medical', 'Healthcare & Medical'), ('Creative, Design & Media', 'Creative, Design & Media'), ('Law, Government & Public Service', 'Law, Government & Public Service'), ('Business, Finance & Administration', 'Business, Finance & Administration'), ('Aviation, Defense & Security', 'Aviation, Defense & Security'), ('Education, Research & Documentation', 'Education, Research & Documentation'), ('Hospitality & Services', 'Hospitality & Services')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.FloatField(validators=[loan_manager.models.validate_loan_amount]),
        ),
    ]
